---
title: "Difference-in-Differences (DiD) Regressions - Census Tracts"
author: "Kevin Okonkwo"
date: "`r Sys.Date()`"
output: html_document
---

## Libraries

```{r Libraries}

library(tidycensus)
library(tidyverse)
library(tmap)
library(sf)
library(here)
library(MatchIt)
library(optmatch)
library(cobalt)
library(readr)
library(modelsummary)
library(broom)
library(hrbrthemes)
library(extrafont)
library(ggthemes)
library(ggplot2)
library(ggpubr)

here()

```

## Loading and preparation of data frames

```{r Data wrangling and preparation}

appended_df <- st_read(here("data/census tracts/outputs/appended_df.shp"))


appended_df <- appended_df %>% 
  select(GEOID, NAME, geometry, year, treatment = tretmnt, distance = distanc,
         weights, subclass = subclss, medhinc_tract = mdhnc_t, medhinc_county = mdhnc_c,
         medhinc_ratio_tract = mdhnc__, income_quintiles = incm_qn, high_inc_mobility = hgh_nc_,
         high_education = hgh_dct, unemployment_rate = unmply_,
         low_inc_hh = lw_nc_h, total_pop = totl_pp, median_age = medin_g, median_rent = mdn_rnt,
         distance_centroid_cbd = dstnc__, after_2013 = af_2013)


appended_df <- appended_df %>%
  mutate(log_medhinc_tract = log(medhinc_tract))


appended_df$year <- as.factor(appended_df$year)

appended_df$treatment <- as.factor(appended_df$treatment)

```

## t-test for unemployment rate and high-income influx of treated units before and after treatment period

```{r t-test of unemployment rate by treatment and time}

appended_df_treated <- appended_df %>% 
  filter(treatment == 1)

appended_df_control <- appended_df %>% 
  filter(treatment == 0)


t.test(unemployment_rate ~ after_2013, data = appended_df_treated)

t.test(unemployment_rate ~ after_2013, data = appended_df_control)


t.test(high_inc_mobility ~ after_2013, data = appended_df_treated)

t.test(high_inc_mobility ~ after_2013, data = appended_df_control)

```

## DiD regressions

```{r DiD models}

# Median household income

model_medhinc <- lm(log_medhinc_tract ~ treatment + after_2013 + (treatment * after_2013) +
                              unemployment_rate + high_inc_mobility  + median_age + total_pop + median_rent + distance_centroid_cbd,
                            data = appended_df)

tidy(model_medhinc)

# Share of low-income households

model_low_inc <- lm(low_inc_hh ~ treatment + after_2013 + (treatment * after_2013) +
                                        unemployment_rate + high_inc_mobility + median_age + total_pop + median_rent + distance_centroid_cbd,
                                      data = appended_df)

tidy(model_low_inc)

```

## DiD regressions for treated sample only

``` {r DiD models (treated sample)}

# Median Household Income

model_medhinc_treated_tracts <- lm(log_medhinc_tract ~ after_2013 + unemployment_rate + high_inc_mobility +
                                median_age + total_pop + median_rent + distance_centroid_cbd,
                                data = appended_df_treated)

tidy(model_medhinc_treated_tracts)


# Share of low-income household

model_low_inc_treated_tracts <- lm(low_inc_hh ~ after_2013 + unemployment_rate + high_inc_mobility +
                                        median_age + total_pop + median_rent + distance_centroid_cbd,
                                      data = appended_df_treated)

tidy(model_low_inc_treated_tracts)

```
