---
title: "Difference-in-Differences (DiD) Plots - Block Groups"
author: "Kevin Okonkwo"
date: "`r Sys.Date()`"
output: html_document
---

## Libraries

```{r Libraries}

library(tidycensus)
library(tidyverse)
library(tmap)
library(sf)
library(here)
library(MatchIt)
library(optmatch)
library(cobalt)
library(readr)
library(modelsummary)
library(broom)
library(hrbrthemes)
library(extrafont)
library(ggthemes)
library(ggplot2)
library(ggpubr)

here()

```

## Loading and preparation of data frames

```{r Data wrangling and preparation}

appended_df <- st_read(here("data/block groups/outputs/appended_df.shp"))

appended_df <- appended_df %>% 
  select(GEOID, NAME, geometry, year, treatment = tretmnt, distance = distanc,
         weights, subclass = subclss, medhinc_block = mdhnc_b, medhinc_county = mdhnc_c,
         medhinc_ratio_block = mdhnc__, income_quintiles = incm_qn, unemployment_rate = unmply_,
         low_inc_hh = lw_nc_h, total_pop = totl_pp, median_age = medin_g, median_rent = mdn_rnt,
         distance_centroid_cbd = dstnc__, after_2013 = af_2013)


appended_df <- appended_df %>%
  mutate(log_medhinc_block = log(medhinc_block))


appended_df$year <- as.factor(appended_df$year)

appended_df$treatment <- as.factor(appended_df$treatment)

```

## Plotting of causal treatment effect for 2013-2022 (uncontrolled)

```{r Causal plot for log. median household income}

diffs <- appended_df %>% 
  group_by(after_2013, treatment) %>% 
  summarize(mean_log_medhinc = mean(log_medhinc_block))


before_treatment <- diffs %>%
  filter(after_2013 == 0, treatment == 1) %>% 
  pull(mean_log_medhinc)

before_control <- diffs %>%
  filter(after_2013 == 0, treatment == 0) %>% 
  pull(mean_log_medhinc)

after_treatment <- diffs %>%
  filter(after_2013 == 1, treatment == 1) %>% 
  pull(mean_log_medhinc)

after_control <- diffs %>%
  filter(after_2013 == 1, treatment == 0) %>% 
  pull(mean_log_medhinc)


diff_treatment_before_after <- after_treatment - before_treatment
diff_control_before_after <- after_control - before_control

diff_diff <- diff_treatment_before_after - diff_control_before_after


treatment_plot_medhinc <- ggplot(data = diffs, aes(x = after_2013, y = mean_log_medhinc, color = factor(treatment))) +
  geom_point(alpha = 0.7, size = 2) +
  geom_line(aes(group = treatment), size = 1) +
  geom_segment(aes(x = 0, xend = 1, y = before_treatment, yend = after_treatment - -0.067, linetype = "Vorhergesagter Trend ohne Erweiterung"), 
               size = 0.8, color = "black") +
  geom_segment(aes(x = 1, xend = 1, y = after_treatment - -0.067, yend = after_treatment, linetype = "Tatsächlicher Trend mit Erweiterung"), 
               size = 0.8, color = "black") +
  labs(
    title = "Log. Medianhaushaltseinkommen vor und nach der E-Line Erweiterung - Block Groups im Zeitraum von 2013-2022", 
    x = "0 = Pre-Erweiterung; 1 = Post-Erweiterung", 
    y = "Log. Medianhaushaltseinkommen",
    color = "Gruppe",
    linetype = "Effekt"
  ) +
  scale_color_manual(
    values = c("blue", "red"), 
    labels = c("Kontrolleinheiten", "Treatmenteinheiten")
  ) +
  scale_x_continuous(limits = c(0, 1), breaks = c(0, 1)) +
  theme_fivethirtyeight() +
  theme(
    axis.title = element_text(size = 12), 
    text = element_text(family = "Rubik"),
    legend.position = "top",
    plot.title = element_text(size = 17)
  )

treatment_plot_medhinc

```

IMPORTANT REMARK: Next chunk overwrites all values and data sets from the previous one as they share the same names! 

```{r Causal plot for share of low-income households}

diffs <- appended_df %>% 
  group_by(after_2013, treatment) %>% 
  summarize(mean_low_inc = mean(low_inc_hh))


before_treatment <- diffs %>%
  filter(after_2013 == 0, treatment == 1) %>% 
  pull(mean_low_inc)

before_control <- diffs %>%
  filter(after_2013 == 0, treatment == 0) %>% 
  pull(mean_low_inc)

after_treatment <- diffs %>%
  filter(after_2013 == 1, treatment == 1) %>% 
  pull(mean_low_inc)

after_control <- diffs %>%
  filter(after_2013 == 1, treatment == 0) %>% 
  pull(mean_low_inc)


diff_treatment_before_after <- after_treatment - before_treatment
diff_control_before_after <- after_control - before_control

diff_diff <- diff_treatment_before_after - diff_control_before_after


treatment_plot_low_inc <- ggplot(data = diffs, aes(x = after_2013, y = mean_low_inc, color = factor(treatment))) +
  geom_point(alpha = 0.7, size = 2) +
  geom_line(aes(group = treatment), size = 1) +
  geom_segment(aes(x = 0, xend = 1, y = before_treatment, yend = after_treatment - 0.010, linetype = "Vorhergesagter Trend ohne Erweiterung"), 
               size = 0.8, color = "black") +
  geom_segment(aes(x = 1, xend = 1, y = after_treatment - 0.010, yend = after_treatment, linetype = "Tatsächlicher Trend mit Erweiterung"), 
               size = 0.8, color = "black") +
  labs(
    title = "Anteil einkommensschwacher Haushalte vor und nach der E-Line Erweiterung - Block Groups im Zeitraum von 2013-2022", 
    x = "0 = Pre-Erweiterung; 1 = Post-Erweiterung", 
    y = "Anteil einkommensschwacher Haushalte (in %) ",
    color = "Gruppe",
    linetype = "Effekte"
  ) +
  scale_color_manual(
    values = c("blue", "red"), 
    labels = c("Kontrolleinheiten", "Treatmenteinheiten")
  ) +
  scale_x_continuous(limits = c(0, 1), breaks = c(0, 1)) +
  theme_fivethirtyeight() +
  theme(
    axis.title = element_text(size = 12), 
    text = element_text(family = "Rubik"),
    legend.position = "top",
    plot.title = element_text(size = 16)
  )

treatment_plot_low_inc

```

